import {
    HiOutlineColorSwatch,
    HiOutlineDesktopComputer,
    HiOutlineTemplate,
    HiOutlineViewGridAdd,
    HiOutlineHome,
    HiOutlineChartSquareBar,
    HiOutlineUserGroup,
    HiOutlineTrendingUp,
    HiOutlineCurrencyDollar,
    HiOutlineBookOpen,
    HiOutlineUserCircle,
    HiOutlineDocumentText,
    HiOutlinePaperAirplane,
    HiOutlineChartPie,
    HiOutlineLockClosed,
    HiOutlineShieldCheck,
    HiOutlineUserAdd,
    HiOutlineKey,
    HiOutlineDocumentDuplicate,
    HiOutlineHand,
    HiOutlineBan,
    HiOutlineShare,
    HiOutlineVariable,
    HiOutlineCode,
    HiOutlineChatAlt,
    HiOutlineCube,
    HiOutlineReceiptTax,
    HiOutlinePhotograph,
} from 'react-icons/hi'

import type { JSX } from 'react'

export type NavigationIcons = Record<string, JSX.Element>

const navigationIcon: NavigationIcons = {
    home: <HiOutlineHome />,
    apps: <HiOutlineViewGridAdd />,
    project: <HiOutlineChartSquareBar />,
    users: <HiOutlineUserGroup />,
    sales: <HiOutlineTrendingUp />,
    crypto: <HiOutlineCurrencyDollar />,
    knowledgeBase: <HiOutlineBookOpen />,
    account: <HiOutlineUserCircle />,
    uiComponents: <HiOutlineTemplate />,
    common: <HiOutlineColorSwatch />,
    feedback: <HiOutlineChatAlt />,
    dataDisplay: <HiOutlineDesktopComputer />,
    forms: <HiOutlineDocumentText />,
    navigation: <HiOutlinePaperAirplane />,
    graph: <HiOutlineChartPie />,
    authentication: <HiOutlineLockClosed />,
    signIn: <HiOutlineShieldCheck />,
    signUp: <HiOutlineUserAdd />,
    forgotPassword: <HiOutlineLockClosed />,
    resetPassword: <HiOutlineKey />,
    pages: <HiOutlineDocumentDuplicate />,
    welcome: <HiOutlineHand />,
    accessDenied: <HiOutlineBan />,
    guide: <HiOutlineBookOpen />,
    documentation: <HiOutlineDocumentText />,
    sharedComponentDoc: <HiOutlineShare />,
    utilsDoc: <HiOutlineVariable />,
    changeLog: <HiOutlineCode />,
    products: <HiOutlineCube />,
    orders: <HiOutlineReceiptTax />,
    assets: <HiOutlinePhotograph />,
}

export default navigationIcon